import Head from 'next/head';
import { MovieContainer, Nav } from '../../components';

export default function MoviesPage() {
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Nav />
      <MovieContainer />
    </div>
  );
}
